[package]
name = "grpc-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13"
prost = "0.13"
tokio = { version = "1", features = ["full"]}
tokio-stream = "0.1"

[build-dependencies]
tonic-build = "0.13"